### ISSUE TITLE
🐛 Failure when button doesn't click

### ISSUE THREAD

**Issue by skadogg** [skadogg/personal-tv-guide#103]
Ran the code on a different computer. It was going great for a while, but then it failed after resetting the connection (close & quit, then get). Hopefully, this is as simple as a try-catch block.

```cmd
DevTools listening on ws://127.0.0.1:64647/devtools/browser/6d3f7a76-d52f-4312-a659-2e5069579f9b
<■■■⚠︎                                    > (!) 74/908 [8%] in 6:00.6 (0.21/s)
Traceback (most recent call last):
  File "c:\Users\gunner\Documents\Git\personal-tv-guide\run.py", line 32, in <module>
    modules.justwatch.scrape_justwatch('Movies')
  File "c:\Users\gunner\Documents\Git\personal-tv-guide\modules\justwatch.py", line 177, in scrape_justwatch
    driver = reset_site_conn(driver)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\gunner\Documents\Git\personal-tv-guide\modules\justwatch.py", line 346, in reset_site_conn
    modules.auto_sign_in.click_through_privacy_model(driver)
  File "c:\Users\gunner\Documents\Git\personal-tv-guide\modules\auto_sign_in.py", line 67, in click_through_privacy_model
    save_settings_button.click()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'click'
PS C:\Users\gunner\Documents\Git\personal-tv-guide>`

**Comment by skadogg** [comment]
I think this was due to transient network issues. It doesn't seem to be happening anymore.
