### ISSUE TITLE
🐛 Error loading list after sign-in

### ISSUE THREAD

**Issue by skadogg** [skadogg/personal-tv-guide#83]
Tried running on a different machine and ran into this error right away.

> Traceback (most recent call last):
>   File "c:\Users\gunner\Documents\Git\personal-tv-guide\run.py", line 32, in <module>
>     modules.justwatch.scrape_justwatch('TV')
>   File "c:\Users\gunner\Documents\Git\personal-tv-guide\modules\justwatch.py", line 127, in scrape_justwatch   
>     pages = (items_in_list // 20) + 1
>              ~~~~~~~~~~~~~~^^~~~
> TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'

Hopefully, it's just a timing issue and we need to wait one or two more seconds before loading the list.

**Comment by skadogg** [comment]
This appears to be working again in v4.1.1.
