### ISSUE TITLE
🐛 Scrape fails when show has no runtime listed

### ISSUE THREAD

**Issue by skadogg** [skadogg/personal-tv-guide#96]
![image](https://github.com/skadogg/personal-tv-guide/assets/19212961/c71892fc-8829-4bc6-897f-abbaa0bfe3c5)

[_Twisters_](https://www.justwatch.com/us/movie/twisters) is coming out later this year, but there's no runtime shown yet. Without a runtime, the _runtime_to_minutes_ function fails:

```
Traceback (most recent call last):
  File "c:\Users\gunner\Documents\git\personal-tv-guide\run.py", line 32, in <module>
    modules.justwatch.scrape_justwatch('Movies')
  File "c:\Users\gunner\Documents\git\personal-tv-guide\modules\justwatch.py", line 275, in scrape_justwatch
    show_runtime_minutes = Activity.runtime_to_minutes(show_runtime, round_up=False)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\gunner\Documents\git\personal-tv-guide\classes\activity.py", line 29, in runtime_to_minutes
    if 'h' in runtime_str:
       ^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

Activity.duration is stored as an int to represent minutes. Maybe upcoming shows should just be ignored.

**Comment by skadogg** [comment]
It does look like #98 does take care of this.

![image](https://github.com/skadogg/personal-tv-guide/assets/19212961/986f0373-0ad1-4a7a-9ec2-893ac088d612)
